###
GET http://localhost:3000/api/habits

###
POST http://localhost:3000/api/habits
Content-Type: application/json

{
  "name": "To Be Deleted"
}

###
PUT http://localhost:3000/api/habits/1
Content-Type: application/json

{
  "name": "50 pushups"
}

###
DELETE http://localhost:3000/api/habits/8